### ISSUE TITLE
Xsolla payment Issue.

### ISSUE THREAD

**Issue by AkioUnity** [xsolla/xsolla-sdk-php#22]
Please check this
https://basecamp.com/2008053/projects/10975817/messages/51091739

![11](https://cloud.githubusercontent.com/assets/11934855/11200793/9894aa50-8d13-11e5-9d18-df367bf572c6.png)

**Comment by sashamexmat** [comment]
Hello Akio,

Your problem was discussed in basecamp and by email, also we've added the special section Troubleshooting in our documentation developers.xsolla.com/#php_troubleshooting.

Please mention that this Github repository is responsible only for the Xsolla PHP SDK, not for the integration generally.
